### ISSUE TITLE
Support for custom FIWARE IdM instances

### ISSUE THREAD

**Issue by aarranz** [martel-innovate/MasterMind#12]
Currently, the code is hardcoded to use FIWARE Lab for authentication. Moreover, it is also hardcoded the callback URL, so you have to deploy MasterMind on `localhost:3000`.

It would be great to be able to configure the FIWARE IdM to use and all the details to connect with it (Client Id, Client Secret, etc).

Best regards.

**Comment by chicco785** [comment]
hi @aarranz thx for the feedback, @Cerfoglg made two PRs in the related repositories, would you mind to review?

https://github.com/martel-innovate/MasterMind-API/pull/13
https://github.com/martel-innovate/MasterMind-UI/pull/13

if you have other requirements feel free to add them as issues.

**Comment by aarranz** [comment]
Hi @chicco785, you are welcome.

Pull requests seems ok (except for the lack of documentation). I have not tested those changes, but I will try to do it ASAP, probably in next days.

**Comment by aarranz** [comment]
Well, sorry for the delay, I have tested it, with current code and it is working 👍 .
